import React from 'react'
import { Card } from 'flowbite-react'
import Head from 'next/head'
import NavbarC from '@/components/NavbarC'
import Footer from '@/components/Footer'
import ProfileCard from '@/components/ProfileCard'

function Profile() {
    return (
        <>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main className='bg-white dark:bg-primary min-h-screen'>
              {/* <NavbarC/>
               */}
               {/* <NavbarC/> */}
            
    
              <ProfileCard/>
            
              {/* <Footer/> */}
            
          </main>
    
        </>
    
      )
}

export default Profile