import React, { useContext, useEffect, useState } from 'react'
import { ListGroup } from 'flowbite-react'
import SingleChat from '@/components/SingleChat'
import ChatInput from '@/components/ChatInput'
import MessageComp from '@/components/MessageComp'

import Head from 'next/head'
import { PolybaseContext } from '@/context/PolybaseProvider'


function Chat() {
const {userRecordRef,chatCollectionReference,userCollectionReference} = useContext(PolybaseContext)

  const[allChats,setAllChats] = useState([]);
  

  const allRenderedChats = allChats.map(c=>{
    return(
      <SingleChat id = {c.id}/>
    )
  })

  useEffect(()=>{
    userRecordRef.onSnapshot (
      (newDoc)=>{
        console.log(newDoc)
        const chats = newDoc.data.approvedChat
        // console.log(chats)
        
        setAllChats(chats)

      },
      (err)=>{
        console.log(err)
      }
    )
    
    
  })

  return (
    <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className='bg-white dark:bg-primary min-h-screen'>
      {/* <NavbarC/> */}
    <div className='w-1/2 m-auto'>

    <ListGroup className=''>
        {allRenderedChats}
        {/* <MessageComp/> */}
        {/* <ChatInput/> */}
    </ListGroup>
    </div>
    {/* <Footer/> */}
    </main>
    </>
      )
}

export default Chat