import React from 'react'
import { ListGroup } from 'flowbite-react'
import SingleChat from '@/components/SingleChat'
import ChatInput from '@/components/ChatInput'
import MessageComp from '@/components/MessageComp'
import NavbarC from '@/components/NavbarC'
import Footer from '@/components/Footer'
import Head from 'next/head'

function Chat() {
  return (
    <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className='bg-white dark:bg-primary min-h-screen'>
      {/* <NavbarC/> */}
    <div className='w-1/2 m-auto'>

    <ListGroup className=''>
        <SingleChat className="flex items-center"/>
        <SingleChat/>
        <SingleChat/>
        <MessageComp/>
        <ChatInput/>
    </ListGroup>
    </div>
    {/* <Footer/> */}
    </main>
    </>
      )
}

export default Chat